### ISSUE TITLE
Google-Play-License-Check

### ISSUE THREAD

**Issue by unbalanced** [KirillKuzyk/Google-Play-License-Check#17]
Hey @KirillKuzyk, hope all is well.
Are you familiar with a package named `com.pairip.licensecheck3` ?
I wonder if it has to do with your Play License Check plugin :)

**Comment by KyryloKuzyk** [comment]
Hi @unbalanced 
I'm not familiar directly with the com.pairip.licensecheck3 but my quick Google search tells me it's an internal Android library. I assume it's a part of Google Play's Licensing service, but it may also serve some other purposes.
