### ISSUE TITLE
Google play billing library 7+

### ISSUE THREAD

**Issue by romanmakhmutov** [KirillKuzyk/Google-Play-License-Check#18]
We're using your plugin and Google requires the developer to update the billing library. Please help!

https://developer.android.com/google/play/billing/migrate-gpblv7

**Comment by KyryloKuzyk** [comment]
Thank you for creating this issue! 

This plugin has no dependencies, including the `com.android.billingclient`. The only dependency that's used by the plugin is the `com.android.vending`, but it's "soft", meaning that it's not used to build the actual app. The `com.android.vending` is accessed at runtime and comes from the Android operating system. And if the OS doesn't have it, the plugin will simply return the `NOT_LICENSED` code.

Can you please add more details to this issue like errors or warnings you receive from Google Play? Do you use any other plugin that depends on `com.android.billingclient`?

**Comment by KyryloKuzyk** [comment]
Hey! I just updated my [game](https://play.google.com/store/apps/details?id=com.stampedegames.projekt&hl=en) that uses this plugin to check the issue and I didn't get any warnings from Google.

Are you sure the warning you receive from Google comes from the "Google Play License Check" plugin and not from some other place in your project?

**Comment by romanmakhmutov** [comment]
It was another plugin, sorry for bothering!

**Comment by KyryloKuzyk** [comment]
@romanmakhmutov I'm glad you managed to find the root cause of the issue!

Can you please update your review on Asset Store?

**Comment by KyryloKuzyk** [comment]
Hey @romanmakhmutov, sorry for bothering you again :)
Can you please update your review on Asset Store if the plugin works for you with no issues? Thanks!
