### ISSUE TITLE
I want to be able to implement it without knowing App Licensing

### ISSUE THREAD

**Issue by IShix-g** [KirillKuzyk/Google-Play-License-Check#7]
I would like to implement it without needing to know the App Licensing specs. The following form is easy to understand. I would appreciate your kind consideration.

```C#
GooglePlayLicense.Check(license =>
{
    // License verification complete
    if (license.IsSuccessCheckLicense)
    {
        // license.status == LicenseStatus.LICENSED
        // || license.status == LicenseStatus.LICENSED_OLD_KEY
        // || license.status == LicenseStatus.NOT_LICENSED
        // || license.status == LicenseStatus.ERROR_OVER_QUOTA
        // || license.status == LicenseStatus.ERROR_NOT_MARKET_MANAGED
        // || license.status == LicenseStatus.ERROR_INVALID_PACKAGE_NAME
        // || license.status == LicenseStatus.ERROR_NON_MATCHING_UID

        // Licensed.
        if (license.HasLicense)
        {
            // license.status == LicenseStatus.LICENSED
            // || license.status == LicenseStatus.LICENSED_OLD_KEY

            if (license.IsSubscribedPlayPass)
            {
                // This user has a license for Google play pass
            }
        }
    }
    else if (!license.HasError)
    {
        // Need to retry to get a license.
        // license.status == LicenseStatus.ERROR_CONTACTING_SERVER
        // || license.status == LicenseStatus.ERROR_SERVER_FAILURE
    }
    
    if (license.HasError)
    {
        // license.status == LicenseStatus.ERROR_INVALID_PACKAGE_NAME
        // || license.status == LicenseStatus.ERROR_NON_MATCHING_UID
    }
});
```

The following would be more helpful

```C#
// Timeout:60s Repeat retries within this number of seconds.
GooglePlayLicense.Check(60, license =>
{
    if (license.IsSuccessCheckLicense
        && license.HasLicense)
    {
        // license.status == LicenseStatus.LICENSED
        // || license.status == LicenseStatus.LICENSED_OLD_KEY
        if (license.IsSubscribedPlayPass)
        {
            // This user has a license for Google play pas
        }
    }
    
    if (license.HasError)
    {
        // license.status == LicenseStatus.ERROR_CONTACTING_SERVER
        // || license.status == LicenseStatus.ERROR_SERVER_FAILURE
        Debug.LogError(license.Error);
    }
});
```

**Comment by KirillKuzyk** [comment]
**IsSubscribedPlayPass**
Unfortunately, it's not possible to check the IsSubscribedPlayPass as described [here](https://github.com/KirillKuzyk/Google-Play-License-Check/discussions/6#discussioncomment-3314455). Play Pass service uses App Licensing to check if a user's app is licensed.
1. For paid games: LICENSED status means that a user has an active Play Pass subscription OR has purchased the paid game.
2. For free games: LICENSED status means that a user has an active Play Pass subscription OR has downloaded the game for free from Google Play. The proposed way by Google to check if the user has access to premium content is [this one](https://github.com/KirillKuzyk/Google-Play-License-Check/discussions/6#discussioncomment-3314455).

**Timeout**
Thank you for the feature request, I'll implement the timeout in the next plugin version.

**Your code suggestions**
Everything else in your code example can be already achieved by the following code:
```
GooglePlayLicense.Check(license => {
    switch (license.status) {
        case LicenseStatus.LICENSED:
            // Licensed
            break;
        case LicenseStatus.ERROR_CONTACTING_SERVER:
        case LicenseStatus.ERROR_SERVER_FAILURE:
            // No need to handle this case, the plugin already has a retry functionality
            break;
        case LicenseStatus.ERROR_INVALID_PACKAGE_NAME:
        case LicenseStatus.ERROR_NON_MATCHING_UID:
            // Handle error
            break;
    }
});
```

**Comment by IShix-g** [comment]
> Thank you for the feature request, I'll implement the timeout in the next plugin version.

Thank you for your consideration.
The timeout is helpful as some countries do not have access to Google Play.

> Everything else in your code example can be already achieved by the following code:

Understood. Thank you for your consideration.
